apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pushgateway
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-pushgateway
    targetRevision: 2.6.0
    helm:
      releaseName: pushgateway
      values: |
        service:
          type: ClusterIP
          port: 9091
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
